osx_image: xcode7
language: objective-c
script:
  - uname -a
  - pwd
  - . travis-scripts/build_mode
  - echo "BUILD_MODE=$BUILD_MODE"
  - travis-scripts/dart.sh
  - travis-scripts/cordova-prepare.sh
