osx_image: xcode7
language: objective-c
rvm: 2.2.3

branches:
  except:
    - /^deployed\/\w+\/\w+\/\w+$/

env:
  global:
    - BUILD_NUM=$TRAVIS_BUILD_NUMBER
    - PROJECT_REPO_SLUG=$TRAVIS_REPO_SLUG
    - GIT_BRANCH=$TRAVIS_BRANCH
  matrix:
    - PLATFORM=android
    - PLATFORM=ios

before_install:
  - brew update || brew update
  - brew install python3
  - sudo pip3 install virtualenv
  - virtualenv --python=$(type -p python3) .v3
  - source .v3/bin/activate
install:
  - python --version

script:
  - build-scripts/start.sh

notifications:
  email: false
  slack:
    secure: cj2UIdsFzOCepZpaSCNTu1g37P2Uhve31f7xKN6kl8E1cAtgftWYCVOE43rCChZ4lKYtK2wtGvjTaRjHfO9M2Wz3GiPZ1Q1rh4ECVpUxz4gEEeMutH989T1S3MwkobQICxgXWZid9W3x4+6MEHIwmqiTWwch2AJsAGYPKU/2dz4=
