osx_image: xcode7
language: objective-c
rvm: 2.2.3

env:
  global:
    - BUILD_NUM="$TRAVIS_BUILD_NUMBER"
    - RELEASE_NOTE_PATH="$(build-scripts/env-release_note.sh $TRAVIS_COMMIT $TRAVIS_COMMIT_RANGE)"
    - IS_CI="$(build-scripts/env-is_ci.sh)"
    - BUILD_MODE="$(build-scripts/env-build_mode.sh)"
  matrix:
    - platform=android
    - platform=ios

before_install:
  - (echo -n 'gem'; echo -n ':'; echo ' --no-document') > $HOME/.gemrc
  - brew update
  - build-scripts/cache.sh load $TRAVIS_REPO_SLUG

install:
  - brew tap dart-lang/dart && brew install dart
  - sudo gem install compass xcodeproj
  - npm install
  - export PATH="$PATH:$(pwd)/node_modules/.bin"
  - build-scripts/cache.sh save $TRAVIS_REPO_SLUG

before_script:
  - build-scripts/dart.sh
  - build-scripts/cordova-prepare.sh

script:
  - build-scripts/${platform}-build.sh
