osx_image: xcode7
language: objective-c
jdk:
  - oraclejdk8
dart: stable
node_js: 0.12

cache:
  bundler: true
  directories:
    - node_modules
    - plugins
    - $HOME/.pub-cache
    - $HOME/.ivy2

install:
  - brew tap dart-lang/dart && brew install dart
  - brew install android
  - brew install sbt
  - npm install
  - gem install compass
  - for dir in $(pwd)/node_modules/*/bin; do export PATH=$PATH:$dir; done; echo $PATH

script:
  - uname -a
  - pwd
  - . travis-scripts/build_mode
  - echo "BUILD_MODE=$BUILD_MODE"
  - travis-scripts/dart.sh
  - travis-scripts/cordova-prepare.sh
  - travis-scripts/android-build.sh
  - travis-scripts/ios-build.sh
