osx_image: xcode7
language: objective-c
node_js: 4.2

branches:
  except:
    - /^deployed\/\w+\/\w+\/\w+$/

env:
  global:
    - BUILD_NUM=$TRAVIS_BUILD_NUMBER
    - PROJECT_REPO_SLUG=$TRAVIS_REPO_SLUG
    - GIT_BRANCH=$TRAVIS_BRANCH
  matrix:
    - PLATFORM=android
    - PLATFORM=ios

before_install:
  - node -v
  - gem install bundle
  - brew update || brew update
  - brew install python3
  - sudo pip3 install virtualenv
  - virtualenv --python=$(type -p python3) .v3
  - source .v3/bin/activate
  - pip install --upgrade wheel
install:
  - pip install boto3
  - build-scripts/cache.py load
  - pip install pyyaml lxml requests
  - brew tap dart-lang/dart && brew install dart
  - bundle install
  - npm install
  - export PATH="$PATH:$(pwd)/node_modules/.bin"
  - build-scripts/cache.py save
  - build-scripts/cache.py load build-scripts/persistent

script:
  - build-scripts/main.py

notifications:
  email: false
  slack:
    secure: cj2UIdsFzOCepZpaSCNTu1g37P2Uhve31f7xKN6kl8E1cAtgftWYCVOE43rCChZ4lKYtK2wtGvjTaRjHfO9M2Wz3GiPZ1Q1rh4ECVpUxz4gEEeMutH989T1S3MwkobQICxgXWZid9W3x4+6MEHIwmqiTWwch2AJsAGYPKU/2dz4=
