osx_image: xcode7
language: objective-c

cache:
  bundler: true
  directories:
    - node_modules
    - plugins
    - $HOME/.pub-cache
    - $HOME/.ivy2
    - $HOME/.gradle

before_install:
  - brew update

install:
  - brew tap dart-lang/dart && brew install dart
  - brew install android
  - export ANDROID_HOME=$(brew --prefix android) && echo $ANDROID_HOME
  - brew install sbt
  - brew install ruby
  - npm install
  - gem install compass cupertino gym
  - for dir in $(pwd)/node_modules/*/bin; do export PATH=$PATH:$dir; done; echo $PATH

before_script:
  - . travis-scripts/build_mode
  - echo "BUILD_MODE=$BUILD_MODE"
  - travis-scripts/dart.sh
  - travis-scripts/cordova-prepare.sh

script:
  - travis-scripts/build.sh

env:
  global:
    - BUILD_NUM="$TRAVIS_BUILD_NUMBER"
  matrix:
    - platform=android
    - platform=ios

after_success:
  - travis-scripts/android-deploy.sh
