osx_image: xcode7
language: objective-c
rvm: 2.2.3

cache:
  bundler: true
  directories:
    - node_modules
    - plugins
    - $HOME/.pub-cache
    - $HOME/.ivy2
    - $HOME/.gradle

env:
  global:
    - BUILD_NUM="$TRAVIS_BUILD_NUMBER"
    - RELEASE_NOTE_PATH="$(build-scripts/env-release_note.sh $TRAVIS_COMMIT)"
    - IS_CI="$(build-scripts/env-is_ci.sh)"
    - BUILD_MODE="$(build-scripts/env-build_mode.sh)"
  matrix:
    - platform=android
    - platform=ios

before_install:
  - (echo -n 'gem'; echo -n ':'; echo ' --no-document') > $HOME/.gemrc
  - brew update
  - (brew install s3cmd && alias s3cmd="$(type -p s3cmd) --access_key $S3_CACHE_ACCESS_KEY --secret_key $S3_CACHE_SECRET_KEY")
  - s3cmd get s3://cache-build/${TRAVIS_REPO_SLUG}/node_modules.tar.bz; tar jxf node_modules.tar.bz

install:
  - brew tap dart-lang/dart && brew install dart
  - sudo gem install compass
  - npm install
  - export PATH="$PATH:$(pwd)/node_modules/.bin"
  - tar jcf node_modules.tar.bz node_modules; s3cmd put node_modules.tar.bz s3://cache-build/${TRAVIS_REPO_SLUG}/node_modules.tar.bz

before_script:
  - build-scripts/dart.sh
  - build-scripts/cordova-prepare.sh

script:
  - build-scripts/${platform}-build.sh
