osx_image: xcode7
language: objective-c
rvm: 2.2.3

cache:
  bundler: true
  directories:
    - node_modules
    - plugins
    - $HOME/.pub-cache
    - $HOME/.ivy2
    - $HOME/.gradle

env:
  global:
    - BUILD_NUM="$TRAVIS_BUILD_NUMBER"
    - RELEASE_NOTE_PATH="$(build-scripts/env-release_note.sh $TRAVIS_COMMIT)"
    - IS_CI="$(build-scripts/env-is_ci.sh)"
    - BUILD_MODE="$(build-scripts/env-build_mode.sh)"
  matrix:
    - platform=android
    - platform=ios

before_install:
  - (echo -n 'gem'; echo -n ':'; echo ' --no-document') > $HOME/.gemrc
  - brew update

install:
  - brew tap dart-lang/dart && brew install dart
  - sudo gem install compass
  - npm install
  - for dir in $(pwd)/node_modules/*/bin; do export PATH=$PATH:$dir; done; echo $PATH

before_script:
  - build-scripts/dart.sh
  - build-scripts/cordova-prepare.sh

script:
  - build-scripts/${platform}-build.sh
