osx_image: xcode7
language: objective-c
rvm: 2.2.3

env:
  global:
    - BUILD_NUM="$TRAVIS_BUILD_NUMBER"
    - RELEASE_NOTE_PATH="$(build-scripts/env-release_note.sh $TRAVIS_COMMIT $TRAVIS_COMMIT_RANGE)"
    - IS_CI="$(build-scripts/env-is_ci.sh)"
    - PROJECT_REPO_SLUG=$TRAVIS_REPO_SLUG
    - BUILD_MODE="$(build-scripts/env-build_mode.sh)"
  matrix:
    - PLATFORM=android
    - PLATFORM=ios

script:
  - build-scripts/start.sh

notifications:
  email: false
  slack:
    secure: cj2UIdsFzOCepZpaSCNTu1g37P2Uhve31f7xKN6kl8E1cAtgftWYCVOE43rCChZ4lKYtK2wtGvjTaRjHfO9M2Wz3GiPZ1Q1rh4ECVpUxz4gEEeMutH989T1S3MwkobQICxgXWZid9W3x4+6MEHIwmqiTWwch2AJsAGYPKU/2dz4=
