osx_image: xcode7
language: objective-c

cache:
  bundler: true
  directories:
    - node_modules
    - plugins
    - $HOME/.pub-cache
    - $HOME/.ivy2
    - $HOME/.gradle

before_install:
  - brew update

install:
  - brew tap dart-lang/dart && brew install dart
  - brew install android
  - export ANDROID_HOME=$(brew --prefix android) && echo $ANDROID_HOME
  - brew install sbt
  - npm install
  - gem install compass cupertino shenzhen
  - for dir in $(pwd)/node_modules/*/bin; do export PATH=$PATH:$dir; done; echo $PATH

before_script:
  - . travis-scripts/build_mode
  - echo "BUILD_MODE=$BUILD_MODE"

script:
  - travis-scripts/dart.sh
  - travis-scripts/cordova-prepare.sh
  - travis-scripts/android-build.sh
  - travis-scripts/ios-prepare-update-bunble-version.sh "${TRAVIS_BUILD_NUMBER}"
  - travis-scripts/ios-build.sh

after_success:
  - travis-scripts/android-deploy.sh
