name: triton_note
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  angular: any
  paper_elements: any
  polymer: any
dev_dependencies:
  crypto: any
  mock: any
  unittest: any
transformers:
- angular
- polymer
