name: triton_note
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  angular: any
  paper_elements: any
  polymer: 0.15.5+4
dev_dependencies:
  mock: any
  unittest: any
transformers:
- angular
- polymer
